apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017 
    protocol: TCP
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-mongodb
  labels:
    app: assessment-mongodb
spec: 
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:  
    metadata:
      labels:
        app: mongodb
    spec:
      containers: 
        - name: mongo
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip"
            - "0.0.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              name: mongo
              hostPort: 27017
              protocol: TCP
          volumeMounts:
          - name: mongo-storage
            mountPath: /usr/src/data
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
        