apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: assessment-primary
  name: bank-api
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 4200
    nodePort: 30081
  selector:
    app: assessment-primary
