apiVersion: v1
data:
  .dockerconfigjson: eeeyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pbyd92Mi8iOnsidXNlcm5hbWUiOiJpbXRpYXoxNTE5IiwicGFzc3dvcmQiOiJlTXVtYmExNTE5IiwiZW1haWwiOiJtdWhhbW1hZC5pbXRpYXpAZW11bWJhLmNvbSIsImF1dGgiOiJhVzEwYVdGNk1UVXhPVHBsVFhWdFltRXhOVEU1In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secrets
type: kubernetes.io/dockerconfigjson
